### ISSUE TITLE
omg nice work!

### ISSUE THREAD

**Issue by jdan** [beurkinger/windows-96#1]
going to auto-close, just saying hi

**Comment by beurkinger** [comment]
Thanks man, I appreciate it ! Out of curiosity, how did you find out about this repo ?

**Comment by jdan** [comment]
https://github.com/jdan/98.css/network/dependents?package_id=UGFja2FnZS0xMTA3MTQ5NTgw :)

**Comment by beurkinger** [comment]
that makes sense ;)
